// PLEASE REFER THE README.md FILE FOR THE SETUP INSTRUCTIONS IN THE ARDUINO IOT CLOUD

#include <ESP32Servo.h>
#include "thingProperties.h"  // This header file will be automatically included and available when the Arduino IoT cloud sketch is set up. DO NOT EDIT THIS FILE.

Servo base_servo, hand_servo, grip_servo;

void setup() {
  // Initialize serial and wait for port to open.
  Serial.begin(115200);
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud (Defined in thingProperties.h)
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information related to the state of network and IoT Cloud connection and errors the higher number the more granular information you’ll get.
     The default is 0 (only errors). Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();

  // Servo pin declaration
  base_servo.attach(13);
  hand_servo.attach(12);
  grip_servo.attach(14);
}

void loop() {
  ArduinoCloud.update();
}

//  The following functions are executed every time new values are received from the IoT Cloud.

void onBaseChange()  {
  base_servo.write(base);
}

void onHandChange()  {
  hand_servo.write(hand);
}

void onGripChange()  {
  if (grip == true){
     for(int i = 0; i <= 45; i++){
       grip_servo.write(i);
       delay(10);
     } 
  }
  if (grip == false){
     for(int i = 45; i >= 0; i--){
       grip_servo.write(i);
       delay(10);
     } 
  }
}
